### ISSUE TITLE
一点建议：用正常公式替换{\theta_{j}}可以吗？

### ISSUE THREAD

**Issue by chencan** [fengdu78/deeplearning_ai_books#17]
比如这样的，不太清楚这是什么写法，真的很难看懂。
${\theta_{j}}:={\theta_{j}}-\alpha \frac{\partial }{\partial {\theta_{j}}}J\left(\theta \right)$

**Comment by cuyl** [comment]
你需要一个类似 [tex-all-the-things](https://chrome.google.com/webstore/detail/tex-all-the-things/cbimabofgmfdkicghcadidpemeenbffn/related)这样的chrome插件
如图：
<img width="792" alt="screen shot 2018-06-07 at 10 50 23 am" src="https://user-images.githubusercontent.com/9765936/41075738-a4ade61e-6a40-11e8-9bd2-3f4a8ffc75ef.png">

**Comment by chencan** [comment]
@cuyl 谢谢
